parameters:
    takeoff.security.regex_admin: "^/staff"
    takeoff.security.regex_root: "^/staff/root"
    takeoff.security.regex_api: "^/api/v[1-9]+"
    takeoff.security.regex_web: "^"

security:
    providers:
        takeoff_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        takeoff_web_user_provider:
            id: sylius.web_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: argon2i
    firewalls:
        admin:
            switch_user: true
            context: admin
            pattern: "%takeoff.security.regex_admin%"
            provider: takeoff_admin_user_provider
            form_login:
                provider: takeoff_admin_user_provider
                login_path: takeoff_admin_login
                check_path: takeoff_admin_login_check
                failure_path: takeoff_admin_login
                default_target_path: takeoff_admin_index
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_admin_security
                csrf_token_id: _csrf_admin_token
            remember_me:
                secret: "%env(APP_SECRET)%"
                path: /staff
                name: CHANG_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: takeoff_admin_logout
                target: takeoff_admin_login
            anonymous: true

#        oauth_token:
#            pattern: ^/oauth/token
#            security: false
#
#        api:
#            pattern: "%takeoff.security.regex_api%/.*"
#            stateless:  true
#            anonymous:  false
#            provider:  dos_oauth

        web:
            switch_user: true
            context: web
            pattern: "%takeoff.security.regex_web%"
            provider: takeoff_web_user_provider
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: takeoff_web_user_provider
                login_path: takeoff_web_login
                check_path: takeoff_web_login_check
                failure_path: takeoff_web_login
                default_target_path: takeoff_account_index
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_web_security
                csrf_token_id: _csrf_web_token
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: CHANG_WEB_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: takeoff_web_logout
                target: takeoff_web_login
                invalidate_session: false
            anonymous: true
#            oauth:
#                resource_owners:
#                    facebook: "/social/login/check-facebook"
#                    google: "/social/login/check-google"
#                    github: "/social/login/check-github"
#                    twitter: "/social/login/check-twitter"
#                login_path: /login
#                failure_path: /login
#                use_forward: false
#                oauth_user_provider:
#                    service: phpmob.oauth.user_provider

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: "_partial_.*", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "_partial_.*", role: ROLE_NO_ACCESS }
        - { path: "_widget_.*", allow_if: "request.isXmlHttpRequest()" }
        - { path: "_ajax_.*", allow_if: "request.isXmlHttpRequest()" }

        - { path: "%takeoff.security.regex_root%/.*", role: ROLE_ROOT }
        - { path: "%takeoff.security.regex_admin%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%takeoff.security.regex_admin%/logout", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%takeoff.security.regex_admin%", role: ROLE_ADMIN }
        #- { path: "%takeoff.security.regex_api%/.*", role: ROLE_API }

        - { path: "^/account", role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMINISTRATION_ACCESS]
        ROLE_ROOT: [ROLE_ADMIN]
