sylius_fixtures:
    suites:
        dev:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                locale:
                    name: "locale"
                    options:
                        custom:
                            - { code: th }
                            - { code: en }
                admin_user:
                    name: "admin_user"
                    options:
                        random: 30
                        custom:
                            -
                                email: "root@chang.com"
                                username: "root"
                                password: "root1234"
                                locale_code: '%locale%'
                                roles: [ ROLE_ROOT ]
                                enabled: true
                            -
                                email: "admin@chang.com"
                                username: "admin"
                                password: "admin1234"
                                locale_code: '%locale%'
                                roles: [ ROLE_ADMIN ]
                                enabled: true
                web_user:
                    name: "web_user"
                    options:
                        random: 30
                        custom:
                            -
                                email: "web@chang.com"
                                username: "web"
                                password: "web1234"
                                locale_code: '%locale%'
                                enabled: true
