takeoff_admin_index:
    path: /staff
    defaults:
        _controller: TakeOff\Controller\AdminController::indexAction

_admin:
    prefix: /staff
    resource: 'routes/_admin/main.yml'

_web:
    resource: 'routes/_web/main.yml'
