cse_web_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: chang.controller.security:loginAction
        _sylius:
            template: "web/security/login.html.twig"
            permission: true
            logged_in_route: ~
            login_check_route: cse_web_login_check
            csrf_parameter: _csrf_web_security
            csrf_token_id: _csrf_web_token

cse_web_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: chang.controller.security:checkAction

cse_web_logout:
    path: /logout
    methods: [GET]

cse_web_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.web_user:createAction
        _sylius:
            event: register
            template: "web/security/register.html.twig"
            redirect:
                route: chang_account_index
                parameters: {}
            form:
                type: Chang\Security\Form\Type\SimpleRegistrationType
                options:
                    data_class: "%sylius.model.web_user.class%"
                    validation_groups:
                        - chang_user
                        - chang_user_registration
                        - chang_user_registration_username

cse_web_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.web_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: cse_web_login

cse_web_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.web_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: cse_web_login

cse_web_user_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: sylius.controller.web_user:verifyAction
        _sylius:
            redirect: cse_account_index
