takeoff_web_index:
    path: /
    defaults:
        _controller: TakeOff\Controller\WebController::indexAction
takeoff_web_test:
    path: /test
    defaults:
        _controller: TakeOff\Controller\WebController::testAction

takeoff_web_flashs:
    path: /flashes
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: web/flashes.html.twig

_security:
    resource: '_security.yml'
