takeoff_admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: chang.controller.security:loginAction
        _login_check_route: takeoff_admin_login_check
        _sylius:
            template: "admin/security/login.html.twig"
            permission: true
            logged_in_route: ~
            csrf_parameter: _csrf_admin_security
            csrf_token_id: _csrf_admin_token

takeoff_admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: chang.controller.security:checkAction

takeoff_admin_logout:
    path: /logout
    methods: [GET]
