parameters:
    chang_page_context_admin:
        layout: 'admin/index.html.twig'
        site:
            url: /staff
            name: TakeOff
        menus:
            quick:
                profile:
                    label: chang.ui.profile
                    route: cse_account_profile_update
                    icon: :account_box
                account:
                    label: chang.ui.account
                    route: cse_account_account_update
                    icon: fas fa-shield-alt
                change_password:
                    label: password
                    route: cse_account_change_password
                    icon: sl-ico-social-github
            account:
                profile:
                    label: chang.ui.profile
                    route: cse_web_test
                    icon: far fa-user
                    linkAttributes:
                        data-modal: chang.ui.profile|trans
                account:
                    label: chang.ui.account
                    route: cse_account_account_update
                    icon: fas fa-shield-alt
                change_password:
                    label: chang.ui.change_password
                    route: cse_account_change_password
                    icon: fas fa-key
            main:
                dashboard:
                    label: Dashboard
                    icon: sl-ico-speedometer
                    child:
                        dashboard:
                            label: Dashboard
                            icon: ':dashboard'
                            child:
                                test:
                                    label: Test
                        example:
                            label: Example
                            icon: ':dashboard'
                            uri: /test
                documents:
                    label: Documents
                    icon: sl-ico-docs
                business:
                    label: Business
                    icon: sl-ico-briefcase
                misc:
                    label: Misc
                    icon: sl-ico-graph
                settings:
                    label: Settings
                    icon: sl-ico-settings
